name: Release to Discord

on:
  release:
    types: [ published ]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD }}
          color: "2105893"
          username: "Release Notification"
          avatar_url: "https://github.com/laravel.png"
          content: "||@everyone||"
          footer_title: "GitHub Releases"
          footer_icon_url: "https://github.com/laravel.png"
          footer_timestamp: true
